version: "3.3"
services:
   database:
           image: mysql
           container_name: bd_wordpress
           restart: always
           environment:
               MYSQL_ROOT_PASSWORD_FILE: /run/secrets/bd_root_password
               MYSQL_DATABASE: db_wordpress
               MYSQL_USER: user_wordpress
               MYSQL_PASSWORD_FILE: /run/secrets/bd_password
            secrets:
               - bd_root_password
               - bd_password
           volumes:
               - bd-data:/var/lib/mysql
   wordpress:
           image: wordpress
           container_name: wordpress
           restart: always
           environment:
               WORDPRESS_DB_HOST: database
               WORDPRESS_DB_USER: user_wordpress
               WORDPRESS_DB_PASSWORD_FILE: /run/secrets/bd_password
               WORDPRESS_DB_NAME: db_wordpress
           secrets:
               -bd_password
           volumes:
               - ./web:/var/www/html
           ports:
               - 9000:80
           depends_on:
               - database

   wordpress-pma:
           image: phpmyadmin/phpmyadmin
           container_name: wordpress-pma
           depends_on:
               - database
           environment:
               - PMA_HOST=database
               - PMA_PORT=3306
               - PMA_ARBITRARY=1
           ports:
               - 8001:80
           restart: always
secrets:
    bd_password:
           file: bd_password.txt
    bd_root_password:
           file: bd_root_password.txt

volumes:
   bd-data: